### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by akatz** [stepanhruda/PostgreSQL-Swift#5]
- [x] Integration testing using Docker (run OS X script on OS X, Linux script on Linux)
- [ ] Consider necessity of asynchronous APIs, and whether to use libdispatch or use libpq's APIs
- [ ] Shadow all desired libpq APIs (multiple tasks here)
- [ ] Look into using Swift Foundation to support column types outside of Swift stdlib (date etc.)
- [x] Connection error handling
- [x] TTY option on connect

**Comment by stepanhruda** [comment]
`PQtty` says

> This is obsolete, since the server no longer pays attention to the TTY setting, but the function remains for backwards compatibility.

so I don't think we need to worry about that.

**Comment by stepanhruda** [comment]
> Connection error handling

I think this is done? It forwards the error string from _psql_, did we want to do anything more there?

**Comment by akatz** [comment]
I agree we have handled the basic case which is what I meant.
